### ISSUE TITLE
Is this project can't be open in godot3

### ISSUE THREAD

**Issue by qza2468** [Ark2000/fancy-particles#1]
I'm using the `godot3.4.4`, when i try to open your project, it turns out like this, and can't be open.
![Screenshot from 2022-11-19 16-23-52](https://user-images.githubusercontent.com/70065298/202842286-f32bce70-4e94-4832-bb16-0a61a9034fb0.png)

if it's necessary to use godot4, as it's in alpha test.

**Comment by Ark2000** [comment]
Yes it's made for Godot4, but Godot3 is also fine.

Just copy the `particles.gd` code to godot 3 project and make some tiny changes, it will work.

For exmaple,

change `@export` to `export`

change `@tool` to `tool`

etc.
